name: Publish-snapshot

on:
  push:
    branches: [ main ]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          servers:
            '[
                  {
                    "id": "github",
                    "username": "${env.GITHUB_USERNAME}",
                    "password": "${env.GITHUB_TOKEN}"
                  }
                ]'

      - name: Cache m2 repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BUILD_ENV: 'github-actions'
